### ISSUE TITLE
500 Error /hello endpoint [High]

### ISSUE THREAD

**Issue by Minus20Five** [softeng-701-group-5/softeng-701-assignment-1#44]
**Bug Summary**

Getting 500 server error when hitting /hello (currently mapped to reddit flow).
See screenshot below.

**Test Case(s)**
N/A (we should have integration tests for this)

---

**Expected behavior**

"hello" string returned as JSON object.
Logger outputs reddit posts.

**Observed Behaviour**

500 server error

**Steps To Reproduce**

1. Populate application.properties with reddit credentials
2. Start spring server
3. Make a GET to /hello 

**Environment**
- Version: latest
- OS: macos (latest)
- Browser: chrome (latest)

---

**Code Examples**

**Stack Trace**
```
java.lang.NullPointerException: null
	at com.feeder.server.providers.reddit.RedditFeedProvider.getFeed(RedditFeedProvider.java:61) ~[classes/:na]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ HTTP GET "/hello" [ExceptionHandlingWebHandler]
Stack trace:
		at com.feeder.server.providers.reddit.RedditFeedProvider.getFeed(RedditFeedProvider.java:61) ~[classes/:na]
		at com.feeder.server.controllers.HelloController.readHello(HelloController.java:28) ~[classes/:na]
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
		at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
		at org.springframework.web.reactive.result.method.InvocableHandlerMethod.lambda$invoke$0(InvocableHandlerMethod.java:147) ~[spring-webflux-5.2.4.RELEASE.jar:5.2.4.RELEASE]
		at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:151) ~[reactor-core-3.3.3.RELEASE.jar:3.3.3.RELEASE]
		at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53) ~[reactor-core-3.3.3.RELEASE.jar:3.3.3.RELEASE]
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:48) ~[reactor-core-3.3.3.RELEASE.jar:3.3.3.RELEASE]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[reactor-core-3.3.3.RELEASE.jar:3.3.3.RELEASE]
		at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:153) ~[reactor-core-3.3.3.RELEASE.jar:3.3.3.RELEASE]
		at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:56) ~[reactor-core-3.3.3.RELEASE.jar:3.3.3.RELEASE]
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:55) ~[reactor-core-3.3.3.RELEASE.jar:3.3.3.RELEASE]
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150) ~[reactor-core-3.3.3.RELEASE.jar:3.3.3.RELEASE]
		at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:67) ~[reactor-core-3.3.3.RELEASE.jar:3.3.3.RELEASE]
		at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:76) ~[reactor-core-3.3.3.RELEASE.jar:3.3.3.RELEASE]
...
```
**Screenshots**
![image](https://user-images.githubusercontent.com/20623467/76266777-74771380-62cd-11ea-8c91-23837e7b7f1a.png)

**Error Report**

---

**Additional context**

**Comment by Minus20Five** [comment]
Seems like `RedditClient` is not initialised, hence `NullPointerException`.

**Comment by PreetPatel** [comment]
Are you sure you're providing application properties?
